### ISSUE TITLE
When full with always showing the last if others card are in 1/3 or 2/3

### ISSUE THREAD

**Issue by issour** [pdmfc/nova-info-card#11]
many thx

**Comment by skoyah** [comment]
Hi there @issour.

If I understand correctly you're saying that if one card is full width, it's always being displayed last.

This is the current Nova behaviour and not specific to this package. 
There are some issues on the Nova repo related to this (https://github.com/laravel/nova-issues/issues/1895, https://github.com/laravel/nova-issues/issues/2053).

You can check another package (https://novapackages.com/packages/ericlagarda/nova-text-card) that does hacks this problem if you need a rapid solution. 

That being said, it is possible we might add this feature in the future.

Will be closing this issue since is not really an issue from this package, but from the framework itself. Feel free to continue the discussion if you want.

**Comment by kuvar0158** [comment]
can anyone give proper answer on above questions
